# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 831, 631))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.homeButton = QtWidgets.QPushButton(self.groupBox_2)
        self.homeButton.setGeometry(QtCore.QRect(10, 30, 41, 23))
        self.homeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon)
        self.homeButton.setObjectName("homeButton")
        self.backButton = QtWidgets.QPushButton(self.groupBox_2)
        self.backButton.setGeometry(QtCore.QRect(10, 60, 81, 23))
        self.backButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon1)
        self.backButton.setObjectName("backButton")
        self.nextButton = QtWidgets.QPushButton(self.groupBox_2)
        self.nextButton.setGeometry(QtCore.QRect(100, 60, 81, 23))
        self.nextButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon2)
        self.nextButton.setObjectName("nextButton")
        self.uploadButton = QtWidgets.QPushButton(self.groupBox_2)
        self.uploadButton.setGeometry(QtCore.QRect(780, 60, 41, 23))
        self.uploadButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadButton.setIcon(icon3)
        self.uploadButton.setObjectName("uploadButton")
        self.fileList = QtWidgets.QTreeWidget(self.groupBox_2)
        self.fileList.setGeometry(QtCore.QRect(10, 90, 811, 531))
        self.fileList.setColumnCount(6)
        self.fileList.setObjectName("fileList")
        self.connectButton = QtWidgets.QPushButton(self.groupBox_2)
        self.connectButton.setGeometry(QtCore.QRect(730, 30, 91, 21))
        self.connectButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/internet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectButton.setIcon(icon4)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "FtpClient"))
        self.fileList.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.fileList.headerItem().setText(1, _translate("MainWindow", "Size"))
        self.fileList.headerItem().setText(2, _translate("MainWindow", "Owner"))
        self.fileList.headerItem().setText(3, _translate("MainWindow", "Group"))
        self.fileList.headerItem().setText(4, _translate("MainWindow", "Time"))
        self.fileList.headerItem().setText(5, _translate("MainWindow", "Mode"))
