# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(319, 265)
        self.registerRadio = QtWidgets.QRadioButton(Dialog)
        self.registerRadio.setGeometry(QtCore.QRect(20, 170, 84, 19))
        self.registerRadio.setObjectName("registerRadio")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label.setObjectName("label")
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setGeometry(QtCore.QRect(20, 40, 211, 21))
        self.nameEdit.setObjectName("nameEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 200, 80, 21))
        self.pushButton.setObjectName("pushButton")
        self.passEdit = QtWidgets.QLineEdit(Dialog)
        self.passEdit.setGeometry(QtCore.QRect(20, 110, 211, 21))
        self.passEdit.setObjectName("passEdit")
        self.visitorRadio = QtWidgets.QRadioButton(Dialog)
        self.visitorRadio.setGeometry(QtCore.QRect(20, 140, 84, 19))
        self.visitorRadio.setChecked(True)
        self.visitorRadio.setObjectName("visitorRadio")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.registerRadio.setText(_translate("Dialog", "Registr"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.label.setText(_translate("Dialog", "Name"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.visitorRadio.setText(_translate("Dialog", "Visitor"))
